project/pairproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("reviews/", include("review.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/review/urls.py
from django.urls import path
from . import views

app_name = "review"

urlpatterns = [
    path("", views.main, name="main"),
    path("index/", views.index, name="index"),
    path("search/", views.search_review, name="search"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/create/", views.create, name="create"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
]

project/review/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    writer = models.CharField(max_length=20)
    review_grade = models.IntegerField(
        default=1, validators=[MinValueValidator(1), MaxValueValidator(10)]
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    movie_pk = models.TextField()


class MovieInfo(models.Model):
    img = models.ImageField(upload_to="images/", null=True)
    movie_name = models.CharField(max_length=20)
    director_name = models.CharField(max_length=10)
    summary = models.TextField(max_length=200)
    running_time = models.IntegerField()
    release = models.DateField(auto_now=False, auto_now_add=False)
    movie_grade = models.IntegerField(default=0)
    vote = models.IntegerField(default=0)
    avg_grade = models.FloatField(default=0)

project/review/forms.py
from django import forms
from .models import Review
from django.forms import ModelForm, TextInput, EmailInput, NumberInput


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = "__all__"
        exclude = ("movie_pk",)
        widgets = {
            "title": forms.TextInput(
                attrs={
                    "placeholder": "리뷰 제목은 30자 이내로 입력해주세요.",
                }
            ),
            "content": forms.Textarea(
                attrs={
                    "placeholder": "",
                }
            ),
            "writer": forms.TextInput(
                attrs={
                    "placeholder": "",
                }
            ),
        }
        labels = {
            "title": "리뷰 제목",
            "content": "내용",
            "writer": "작성자",
            "review_grade": "평점",
        }

project/review/views.py
from django.shortcuts import render, redirect
from .forms import ReviewForm
from .models import MovieInfo, Review


def index(request):
    reviews = Review.objects.order_by("-pk")
    Review_len = len([*Review.objects.all()])
    context = {
        "reviews": reviews,
        "Review_len": Review_len,
    }

    return render(request, "review/index.html", context)


def main(request):
    movie_info = MovieInfo.objects.all()
    Review_len = len([*Review.objects.all()])
    context = {
        "movie_info": movie_info,
        "Review_len": Review_len,
    }
    return render(request, "review/main.html", context)


def create(request, pk):
    Review_len = len([*Review.objects.all()])
    movie_info = MovieInfo.objects.get(pk=pk)
    if request.method == "POST":
        review_form = ReviewForm(request.POST)
        grade = int(request.POST.get("review_grade"))
        if review_form.is_valid():
            review_form.save()
            review = Review.objects.order_by("-pk")[0]
            # 처음에 movie_title = movie_info.movie_name 으로 했다가 pk 로 하는게 나을거같아서 pk 로 바꿈
            review.movie_pk = movie_info.pk
            review.save()
            movie_info.movie_grade += grade
            movie_info.vote += 1
            movie_info.avg_grade = movie_info.movie_grade / movie_info.vote
            movie_info.save()
            return redirect("review:index")

    else:
        review_form = ReviewForm()

    context = {
        "review_form": review_form,
        "movie_title": movie_info.movie_name,
        "Review_len": Review_len,
    }

    return render(request, "review/create.html", context)


def detail(request, pk):
    Review_len = len([*Review.objects.all()])
    review = Review.objects.get(pk=pk)

    context = {
        "review": review,
        "Review_len": Review_len,
    }

    return render(request, "review/detail.html", context)


def update(request, pk):
    Review_len = len([*Review.objects.all()])
    review = Review.objects.get(pk=pk)
    old_grade = review.review_grade
    if request.method == "POST":
        review_form = ReviewForm(request.POST, instance=review)

        if review_form.is_valid():
            review_form.save()
            review = Review.objects.get(pk=pk)
            new_grade = review.review_grade
            if old_grade != new_grade:
                movie_pk = review.movie_pk
                movie_info = MovieInfo.objects.get(pk=movie_pk)
                movie_info.movie_grade -= old_grade
                movie_info.movie_grade += new_grade
                movie_info.avg_grade = movie_info.movie_grade / movie_info.vote
                movie_info.save()
            else:
                pass

            return redirect("review:detail", review.pk)

    else:
        review_form = ReviewForm(instance=review)

    context = {
        "review": review,
        "review_form": review_form,
        "Review_len": Review_len,
    }

    return render(request, "review/update.html", context)


def delete(request, pk):
    review = Review.objects.get(pk=pk)
    grade = review.review_grade
    movie_pk = review.movie_pk
    # 처음에 movie_title 로 했다가 pk 로 하는게 나을거같아서 pk 로 바꿈
    movie_info = MovieInfo.objects.get(pk=movie_pk)
    movie_info.movie_grade -= grade
    movie_info.vote -= 1
    if movie_info.vote:
        movie_info.avg_grade = movie_info.movie_grade / movie_info.vote
    else:
        movie_info.avg_grade = 0
    movie_info.save()
    review.delete()

    return redirect("review:index")


def search_review(request):
    review_title = request.GET.get("review-title")
    Review_len = len([*Review.objects.all()])
    retrieved_review_data = Review.objects.filter(title__icontains=review_title)
    context = {
        "retrieved_review_data": retrieved_review_data,
        "Review_len": Review_len,
    }

    return render(request, "review/index.html", context)

project/review/templates/review/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}


{% block content %}

<div class="container my-5" style="width: 600px">
  <div class="p-4"
    style="border:solid 1px #34363c; box-shadow: 4px 12px 30px 6px rgb(0 0 0 / 9%); border-radius: 15px;">
    <form action="" method="POST" enctype="multipart/formdata">
      {% csrf_token %}
      <h1 class="mb-3">{{ movie_title }}</h1>
      {% bootstrap_form review_form %}
      <div class="form-text">
        평점은 1점부터 10점 사이입니다.
      </div>
      <div class="d-flex gap-2 justify-content-end">
        <input type="submit" class="btn" style="width: 85px; background-color: #ff0558; color: white;" value="작성완료">
      </div>
    </form>
  </div>
</div>

{% endblock %}

project/review/templates/review/detail.html
{% extends 'base.html' %}

<!-- Content -->
{% block content %}

<div class="container my-5" style="width: 600px">
  <div class="p-4" style="box-shadow: 4px 12px 30px 6px rgb(0 0 0 / 9%); border-radius: 15px;">
    <div class="d-flex justify-content-end">
      <a class="mx-1" href="{% url 'review:update' review.pk %}" style="color: #35C5F0">수정</a>
      <a class="mx-1" href="{% url 'review:delete' review.pk %}" style="color: #f77">삭제</a>
    </div>
    <h1>{{ review.title }}</h1>
    <br>
    <p>{{ review.content }}</p>
    <p>{{ review.img }}</p>
    <div class="d-flex gap-2 justify-content-end">
      <a href="{% url 'review:index' %}" class="btn"
        style="width: 95px; background-color: #ff0558; color: white;">목록으로</a>
    </div>
  </div>
</div>

{% endblock %}

project/review/templates/review/index.html
{% extends 'base.html' %}

<!-- Content -->
{% block content %}

<div class="d-flex justify-content-center my-5">
  <div class="d-flex justify-content-center flex-wrap p-2 card-wrap" style="width: 1440px;">
    {% if retrieved_review_data %}
    <!-- for retrieved_review_data -->
    {% for review in retrieved_review_data %}
    <a href="{% url 'review:detail' review.pk %}" style="text-decoration: none;">
      <div class="p-4 mt-2 mb-5 mx-3 contentcard"
        style="width: 301px; box-shadow: 4px 12px 30px 6px rgb(0 0 0 / 9%); border-radius: 15px;">
        <h3>{{ review.title }}</h3>
        <hr>
        <p class="mt-4 card-p">{{ review.content }}</p>
      </div>
    </a>
    {% endfor %}
    {% else %}
    <!-- for reviews -->
    {% for review in reviews %}
    <a href="{% url 'review:detail' review.pk %}">
      <div class="p-4 mt-2 mb-5 mx-3 contentcard"
        style="width: 301px; box-shadow: 4px 12px 30px 6px rgb(0 0 0 / 9%); border-radius: 15px; ">
        <h3>{{ review.title }}</h3>
        <hr>
        <p class="mt-4 card-p">{{ review.content }}</p>
      </div>
    </a>
    {% endfor %}
    {% endif %}
  </div>
</div>

{% endblock %}

project/review/templates/review/main.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-center my-5">
  <div class="d-flex justify-content-center flex-wrap p-2 pb-5" style="width: 1440px;">
    {% for movie in movie_info %}
    <a href="{% url 'review:create' movie.id %}">
      <div class="mt-2 mb-4 mx-3 contentcard"
        style="width: 311px; box-shadow: 4px 12px 30px 6px rgb(0 0 0 / 9%); border-radius: 15px;">
        <div class="card-top">
          <div>
            <img style="width: 311px; height: 350px; border-radius: 15px 15px 0 0;" src="{{ movie.img.url }}">
          </div>
        </div>
        <div class="card-body p-4" style="border-radius: 0 0 15px 15px; position: relative;">
          <div class="">
            <h3 class="">{{ movie.movie_name }}</h3>
            <p class="m-0">{{ movie.director_name }} <span class="fw-lighter">| {{ movie.release}} </span>
            </p>
            <p class="m-0"><span style="color: #ff0558">★</span>{{ movie.avg_grade|floatformat }} </p>
            <svg style="position: absolute; top: 19px; right: 22px;" xmlns="http://www.w3.org/2000/svg" width="24"
              height="24" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
              <path fill-rule="evenodd"
                d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z" />
            </svg>
          </div>
        </div>
      </div>
    </a>
    {% endfor %}
  </div>
</div>

{% endblock %}

project/review/templates/review/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}


{% block content %}

<div class="container my-5" style="width: 600px">
  <div class="p-4" style="box-shadow: 4px 12px 30px 6px rgb(0 0 0 / 9%); border-radius: 15px;">
    <form action="" method="POST" enctype="multipart/formdata">
      {% csrf_token %}
      {% bootstrap_form review_form %}
      <div class="form-text">
        평점은 1점부터 10점 사이입니다.
      </div>
      <div class="d-flex gap-2 justify-content-end">
        <input type="submit" class="btn" style="width: 85px; background-color: #35C5F0; color: white;" value="작성완료">
      </div>
    </form>
  </div>
</div>

{% endblock %}

project/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<!-- Head -->

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <!-- Main CSS -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="shortcut icon" href="{% static 'css/film.png' %}">
  <title>Movies</title>
</head>

<!-- Body -->

<body>

  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg bg-light text-dark position-sticky top-0" style="opacity: 0.95;">
    <div class="container">
      <a class="navbar-brand text-dark" href="{% url 'review:main' %}">
        <img src="https://cdn.pixabay.com/photo/2016/06/28/13/50/cat-1484725_1280.png" width="35px">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 align-items-center">
          <li class="nav-item">
            <a class="nav-link text-dark" aria-current="page" href="{% url 'review:main' %}">메인</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-dark" href="{% url 'review:index' %}">리뷰</a>
          </li>
        </ul>

        <!-- Search -->
        <a class="nav-link text-dark px-3" href="https://github.com/jincde/django-pair-movie2" target="_blank">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-github"
            viewBox="0 0 16 16">
            <path
              d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z" />
          </svg>
        </a>
        <form action="{% url 'review:search' %}" class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="리뷰 검색" name="review-title" style="width: 250px;">
          <input class="btn btn-light" type="submit" value="검색">
        </form>
      </div>
    </div>
  </nav>

  <!-- Content -->
  {% block content %}
  {% endblock content %}

  <!-- Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
    crossorigin="anonymous"></script>
  <footer class="py-3 bg-light bottom-0 w-100 text-center">
    <div class="my-3">
      <h3 class="my-0">지금까지 <span style="color: #ff0558">★{{ Review_len }}개의 리뷰</span>가 쌓였어요.
    </div>
    <h3 class="text-secondary fs-6 mt-3 pb-3">
      <p class="my-0">
        7. Oct. 2022.
      </p>
      <p class="my-0">
        Created by 장영진, 조병진, 문현동
      </p>
    </h3>
  </footer>
</body>

</html>